### ISSUE TITLE
Search filter with brackets yields no result

### ISSUE THREAD

**Issue by stiller-leser** [ldapts/ldapts#18] opened 2019-04-24 13:16 UTC
Hey @jgeurts ,

first off thank you very much for the work. 

I am experiencing an issue with the following query:

```
const searchResult: any = await client.search(settings.ldapGroupSearchDN, {
      filter: "(&(objectCategory=group)(displayName=My group (something)",
})
```
After replacing the brackets with `\28` and `\29` this call yields no result. However running: `ldapsearch -H ldaps://.... -x -w 'verySecret' -D myUser -b 'ldapGroupSearchDN' "(&(objectCategory=group)(displayName=My group \28something\29))"` does.

Any pointer why this is?

### Also:
Is there a reason why https://github.com/ldapts/ldapts/blob/master/src/filters/Filter.ts#L36 is protected? Would be cool, if I'd be able to use it. Currently I need to fallback to https://github.com/tcort/ldap-escape before executing the call above (or manually use `.replace()`). Otherwise I see ` UnhandledPromiseRejectionWarning: Error: Illegal unescaped character: ( in value: My group (something at Function._unescapeHexValues (ldapts/dist/FilterParser.js:272:27)`

Best regards,
stiller-leser

**Comment by jgeurts** [comment] 2019-04-24 14:24
Thanks for the report! I'll take a look and see what I can dig up about what's going on... 

As for the protected method, I can't think of any meaningful reason for it to stay protected, so I can make it public for the next release.

**Comment by stiller-leser** [comment] 2019-04-24 15:21
Hey,

oh boy that was fast :)

Thank you very much for the feedback. From what I can tell (reverting the buffer in the _send method to string) it looks as if the request goes out correct (i.e. the brackets are replaced by the number codes). From looking at the options object in the SearchRequest it looks as if the filter has a `\\` in it...

If all it takes to make this method public is removing the `protected` from the method, I am happy to create a PR.

**Comment by jgeurts** [comment] 2019-04-24 15:58
Thanks for the PR! If you are able to reproduce the filter issue with a test, that would be helpful! I'm thinking this might be related to #16, so I'm trying to write some tests that show the incorrect behavior with expected results.

**Comment by jgeurts** [comment] 2019-04-24 20:06
I did notice that your example above was missing a closing parens. Does the following work for you?

```js
const searchResult: any = await client.search(settings.ldapGroupSearchDN, {
  filter: "(&(objectCategory=group)(displayName=My group \28something\29))",
});
```

I added a test for that to v1.5.0 and it produces the expected Filter objects.

**Comment by stiller-leser** [comment] 2019-04-25 08:45
Hi, yeah that parens went missing during my code cleanup for this issue. 

However, I did realize that I have been using ldapts the wrong way. I now use `AndFilter` as well as `EqualityFilter`. The output is - as you said - correct (`(&(objectCategory=group)(displayName=My group \28something\29))`). Also: There is no need for the `Filter.escape` method anymore, since the cleanup now works automatically ;)

However, I still can't seem to get an answer from my ldap server. I keep seeing `{ searchEntries: [], searchReferences: [] }` instead of the actual group. I even checked the `search reference` when using `ldapsearch` and `ldapts`. In both cases it is `ldaps://my.corporation/CN=Configuration,DC=my,DC=corporation`.

**Comment by jgeurts** [comment] 2019-04-25 11:43
I’m not sure how to help more on this unless we can reproduce it with a test hitting jumpcloud or forumsys’ ldap servers (or other public ldap server). 

It might be a little work, but could you capture the request sent from ldapts and ldapsearch to see how they differ? I might be able to help with that, in a few days, since parsing the response might not matter if the requests differ.

**Comment by stiller-leser** [comment] 2019-04-25 11:46
Unfortunately I do not have access to the LDAP server... The `*` workaround is good enough for the moment (as the result is presented in a dropdown to users).

I checked the forumsys ldap server. It doesn't seem like they have groups with `()` in them (at least it is not documented).

I'll see if I can come up with an example in the near future.

Thank you very much for the help though!

**Comment by jgeurts** [comment] 2019-04-25 14:53
I made a group in jumpcloud called `Something (Special)`. Hopefully that helps us try to reproduce the issue!

**Closed** 2019-05-09 21:43 UTC

**Comment by stiller-leser** [comment] 2019-06-05 08:01
Just as a FYI: finally came around to test this. Works perfectly. Thank you for your support here!
